"""Agregando columna genre a la tabla Movie

Revision ID: 3028a7ad6bbe
Revises: 5a7b8d89e5dd
Create Date: 2025-03-18 18:01:44.836039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3028a7ad6bbe'
down_revision = '5a7b8d89e5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('actors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('metascore', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('metascore')
        batch_op.drop_column('revenue')
        batch_op.drop_column('votes')
        batch_op.drop_column('rating')
        batch_op.drop_column('runtime')
        batch_op.drop_column('year')
        batch_op.drop_column('actors')
        batch_op.drop_column('director')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
